
const D=window.APP_DATA,root=document.getElementById('app');
let state=JSON.parse(localStorage.getItem('b1state')||'{"xp":0,"done":[],"wrong":[]}');
function save(){localStorage.setItem('b1state',JSON.stringify(state))}
function lessons(){return D.themes.flatMap(t=>t.lessons.map(l=>({...l,tid:t.id})))} function total(){return lessons().length}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function shell(body){root.innerHTML=`<header><h1>🇳🇱 Mijn B1 Nederlands</h1><p>A2 → B1 · leren met plezier</p></header><div class="wrap"><div class="nav"><button onclick="home()">🏠 Home</button><button onclick="progress()">📊 Voortgang</button><button onclick="daily()">🎯 Vandaag</button></div>${body}</div><div class="footer">Je voortgang wordt alleen op dit apparaat opgeslagen.</div>`}
function home(){let p=Math.round(state.done.length/total()*100);shell(`<div class="card"><div class="big">👋 Hallo!</div><p>Jouw persoonlijke B1 Nederlands-leerapp.</p><p>⭐ <b>${state.xp} XP</b> · ${state.done.length}/${total()} lessen</p><div class="bar"><div style="width:${p}%"></div></div></div><h2>📚 Thema's</h2><div class="grid">${D.themes.map(t=>`<div class="card theme" onclick="theme(${t.id})"><h3>${t.id}. ${esc(t.title)}</h3><p class="muted">${t.lessons.length} lessen</p>${t.lessons.map(l=>`<span class="pill">${l.id}</span>`).join('')}</div>`).join('')}</div>`)}
function theme(id){let t=D.themes.find(x=>x.id===id);shell(`<button class="back" onclick="home()">← Alle thema's</button><div class="card"><h2>${t.id}. ${esc(t.title)}</h2>${t.lessons.map(l=>`<div class="lesson" onclick="lesson(${t.id},'${l.id}')"><b>${l.id} · ${esc(l.title)}</b><div>${l.skills.map(s=>`<span class="pill">${esc(s)}</span>`).join('')}</div><div class="muted">🧩 ${l.grammar.map(g=>esc(g)).join(' · ')}</div></div>`).join('')}</div>`)}
function lesson(tid,lid){let t=D.themes.find(x=>x.id===tid),l=t.lessons.find(x=>x.id===lid);shell(`<button class="back" onclick="theme(${tid})">← ${esc(t.title)}</button><div class="card"><h2>${l.id} · ${esc(l.title)}</h2><p>${l.skills.map(s=>`<span class="pill">${esc(s)}</span>`).join('')}</p><h3>🧩 Grammatica</h3><ul>${l.grammar.map(g=>`<li>${esc(g)}</li>`).join('')}</ul></div><div class="card"><h2>🖼️ Woordenschat</h2>${l.words.map(w=>`<div class="word card" style="box-shadow:none;border:1px solid #eee"><div class="emoji">${w[2]}</div><div><h2>${esc(w[0])}</h2><div class="en">🇬🇧 ${esc(w[1])}</div><div class="example">Maak zelf een zin met <b>${esc(w[0])}</b>.</div></div></div>`).join('')}</div><div class="card"><h2>🎮 Oefenen</h2><p>Test jezelf met woordenschat en grammatica.</p><button class="btn" onclick="quiz(${tid},'${lid}')">Start quiz →</button></div><div class="card"><h2>🗣️ Spreken</h2><p><b>${esc(l.skills[0])}</b></p><p class="muted">Praat 30 seconden. Later kunnen we hier echte AI-spraakfeedback aan koppelen.</p><button class="btn secondary" onclick="alert('Spraakfunctie staat gepland voor versie 2.')">🎤 Start spreken</button></div><div class="card center"><button class="btn" onclick="complete(${tid},'${lid}')">${state.done.includes(l.id)?'✓ Afgerond':'Markeer als afgerond'}</button></div>`)}
function quiz(tid,lid){let t=D.themes.find(x=>x.id===tid),l=t.lessons.find(x=>x.id===lid),q=l.words.slice(0,5).map((w,i)=>({q:`Wat betekent “${w[0]}”?`,o:[w[1],l.words[(i+1)%l.words.length][1],l.words[(i+2)%l.words.length][1]],c:0}));if(tid===1&&lid==='1A')q.push({q:'Welke zin is correct?',o:['Ik heb gisteren gewerkt.','Ik ben gisteren gewerkt.','Ik was gisteren gewerkt.'],c:0});if(tid===2&&lid==='2B')q.push({q:'Welke vorm past bij een wens of hypothetische situatie?',o:['zou','zal','heb'],c:0});if(tid===6&&lid==='6B')q.push({q:'Welke zin gebruikt “aan het” correct?',o:['Ik ben aan het lezen.','Ik heb aan het lezen.','Ik was aan het lezen geweest.'],c:0});if(tid===8&&lid==='8A')q.push({q:'Welke zin is passief?',o:['De e-mail wordt verstuurd.','Ik verstuur de e-mail.','Ik heb de e-mail verstuurd.'],c:0});let i=0,score=0;function render(){let x=q[i];root.innerHTML=`<header><h1>🎮 ${esc(l.id)} · Quiz</h1><p>${esc(l.title)}</p></header><div class="wrap"><div class="card"><p>Vraag ${i+1} van ${q.length} · ⭐ ${score*10} XP</p><h2>${esc(x.q)}</h2><div class="options">${x.o.map((o,j)=>`<button class="option" onclick="pick(this,${j},${x.c})">${esc(o)}</button>`).join('')}</div><p id="fb"></p><button id="next" class="btn hide" onclick="next()">Volgende →</button></div><button class="back" onclick="lesson(${tid},'${lid}')">← Terug</button></div>`}window.pick=(b,j,c)=>{document.querySelectorAll('.option').forEach(x=>x.disabled=true);let ok=j===c;b.classList.add(ok?'correct':'wrong');if(!ok)document.querySelectorAll('.option')[c].classList.add('correct');document.getElementById('fb').textContent=ok?'✅ Goed! +10 XP':'❌ Het juiste antwoord staat groen.';if(ok)score++;document.getElementById('next').classList.remove('hide')};window.next=()=>{i++;if(i<q.length)render();else{state.xp+=score*10;save();root.innerHTML=`<header><h1>🎉 Klaar!</h1></header><div class="wrap"><div class="card center"><div class="big">${score}/${q.length}</div><p>Je hebt ${score*10} XP verdiend.</p><button class="btn" onclick="lesson(${tid},'${lid}')">Verder oefenen</button></div></div>`}};render()}
function complete(tid,lid){if(!state.done.includes(lid)){state.done.push(lid);state.xp+=25;save()}lesson(tid,lid)}
function progress(){let p=Math.round(state.done.length/total()*100);shell(`<div class="card"><h2>📊 Mijn voortgang</h2><div class="big">${p}%</div><p>${state.done.length} van ${total()} lessen · ⭐ ${state.xp} XP</p><div class="bar"><div style="width:${p}%"></div></div></div><div class="grid">${D.themes.map(t=>`<div class="card"><h3>${t.id}. ${t.title}</h3>${t.lessons.map(l=>`<p>${state.done.includes(l.id)?'✅':'⬜'} ${l.id} ${l.title}</p>`).join('')}</div>`).join('')}</div>`)}
function daily(){let a=lessons(),l=a[new Date().getDate()%a.length];shell(`<div class="card"><h2>🎯 Dagelijkse uitdaging</h2><p class="muted">Vandaag:</p><h2>${l.id} · ${esc(l.title)}</h2><p>${l.skills.join(' · ')}</p><button class="btn" onclick="quiz(${l.tid},'${l.id}')">Start challenge →</button></div>`)}
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});home();
